name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 0 * * *" # jalan tiap jam 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake ğŸ
        uses: Platane/snk@v3
        with:
          github_user_name: acaxoxo
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push Snake Animation to Output Branch ğŸ
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
